In [2]:
import pandas as pd

In [3]:
url = r"D:\Courses\Data engineering\Projects\2\International football results from 1872 to 2026\results.csv"
df = pd.read_csv(url)

In [4]:
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0,0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4,2,Friendly,London,England,False
2,1874-03-07,Scotland,England,2,1,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2,2,Friendly,London,England,False
4,1876-03-04,Scotland,England,3,0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49542,2026-08-16,Malaysia,Vietnam,0,2,ASEAN Championship,Kuala Lumpur,Malaysia,False
49543,2026-08-18,Thailand,Singapore,1,2,ASEAN Championship,Bangkok,Thailand,False
49544,2026-08-19,Vietnam,Malaysia,2,0,ASEAN Championship,Hanoi,Vietnam,False
49545,2026-08-22,Thailand,Vietnam,0,2,ASEAN Championship,Bangkok,Thailand,False
49546,2026-08-26,Vietnam,Thailand,2,2,ASEAN Championship,Hanoi,Vietnam,False

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49547 entries, 0 to 49546
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49547 non-null  str
 1   home_team   49547 non-null  str
 2   away_team   49547 non-null  str
 3   home_score  49547 non-null  int64
 4   away_score  49547 non-null  int64
 5   tournament  49547 non-null  str
 6   city        49547 non-null  str
 7   country     49547 non-null  str
 8   neutral     49547 non-null  bool
dtypes: bool(1), int64(2), str(6)
memory usage: 5.9 MB

In [6]:
df.isnull().sum()

date          0
home_team     0
away_team     0
home_score    0
away_score    0
tournament    0
city          0
country       0
neutral       0
dtype: int64

In [7]:
df[df.duplicated()]

Empty DataFrame
Columns: [date, home_team, away_team, home_score, away_score, tournament, city, country, neutral]
Index: []

In [8]:
df.shape

(49547, 9)

In [9]:
df.nunique()

date          16507
home_team       328
away_team       322
home_score       26
away_score       22
tournament      202
city           2093
country         269
neutral           2
dtype: int64

In [10]:
pd.to_datetime(df['date'], errors='coerce').isnull().sum()

np.int64(0)

In [11]:
df['date'] = pd.to_datetime(df['date'])

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49547 entries, 0 to 49546
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49547 non-null  datetime64[us]
 1   home_team   49547 non-null  str
 2   away_team   49547 non-null  str
 3   home_score  49547 non-null  int64
 4   away_score  49547 non-null  int64
 5   tournament  49547 non-null  str
 6   city        49547 non-null  str
 7   country     49547 non-null  str
 8   neutral     49547 non-null  bool
dtypes: bool(1), datetime64[us](1), int64(2), str(5)
memory usage: 5.4 MB

In [13]:
df['home_score'].min(),df['away_score'].min()

(np.int64(0), np.int64(0))

In [14]:
df['home_score'].max(), df['away_score'].max()

(np.int64(31), np.int64(21))

In [15]:
df['neutral'] = df['neutral'].astype(int)

In [16]:
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0,0,Friendly,Glasgow,Scotland,0
1,1873-03-08,England,Scotland,4,2,Friendly,London,England,0
2,1874-03-07,Scotland,England,2,1,Friendly,Glasgow,Scotland,0
3,1875-03-06,England,Scotland,2,2,Friendly,London,England,0
4,1876-03-04,Scotland,England,3,0,Friendly,Glasgow,Scotland,0
...,...,...,...,...,...,...,...,...,...
49542,2026-08-16,Malaysia,Vietnam,0,2,ASEAN Championship,Kuala Lumpur,Malaysia,0
49543,2026-08-18,Thailand,Singapore,1,2,ASEAN Championship,Bangkok,Thailand,0
49544,2026-08-19,Vietnam,Malaysia,2,0,ASEAN Championship,Hanoi,Vietnam,0
49545,2026-08-22,Thailand,Vietnam,0,2,ASEAN Championship,Bangkok,Thailand,0
49546,2026-08-26,Vietnam,Thailand,2,2,ASEAN Championship,Hanoi,Vietnam,0

In [17]:
def get_result(row):
    if row['home_score'] > row['away_score']:
        return 'H'
    elif row['home_score'] < row['away_score']:
        return 'A'
    else : 
        return 'D'
    
df['result'] = df.apply(get_result,axis=1)

In [18]:
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result
0,1872-11-30,Scotland,England,0,0,Friendly,Glasgow,Scotland,0,D
1,1873-03-08,England,Scotland,4,2,Friendly,London,England,0,H
2,1874-03-07,Scotland,England,2,1,Friendly,Glasgow,Scotland,0,H
3,1875-03-06,England,Scotland,2,2,Friendly,London,England,0,D
4,1876-03-04,Scotland,England,3,0,Friendly,Glasgow,Scotland,0,H
...,...,...,...,...,...,...,...,...,...,...
49542,2026-08-16,Malaysia,Vietnam,0,2,ASEAN Championship,Kuala Lumpur,Malaysia,0,A
49543,2026-08-18,Thailand,Singapore,1,2,ASEAN Championship,Bangkok,Thailand,0,A
49544,2026-08-19,Vietnam,Malaysia,2,0,ASEAN Championship,Hanoi,Vietnam,0,H
49545,2026-08-22,Thailand,Vietnam,0,2,ASEAN Championship,Bangkok,Thailand,0,A
49546,2026-08-26,Vietnam,Thailand,2,2,ASEAN Championship,Hanoi,Vietnam,0,D

In [19]:
df['year'] = df['date'].dt.year
df_modern = df[df['year']>=2000].copy()

In [20]:
df_modern

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result,year
24062,2000-01-04,Egypt,Togo,2,1,Friendly,Aswan,Egypt,0,H,2000
24063,2000-01-07,Tunisia,Togo,7,0,Friendly,Tunis,Tunisia,0,H,2000
24064,2000-01-08,Trinidad and Tobago,Canada,0,0,Friendly,Port of Spain,Trinidad and Tobago,0,D,2000
24065,2000-01-09,Burkina Faso,Gabon,1,1,Friendly,Ouagadougou,Burkina Faso,0,D,2000
24066,2000-01-09,Guatemala,Armenia,1,1,Friendly,Los Angeles,United States,1,D,2000
...,...,...,...,...,...,...,...,...,...,...,...
49542,2026-08-16,Malaysia,Vietnam,0,2,ASEAN Championship,Kuala Lumpur,Malaysia,0,A,2026
49543,2026-08-18,Thailand,Singapore,1,2,ASEAN Championship,Bangkok,Thailand,0,A,2026
49544,2026-08-19,Vietnam,Malaysia,2,0,ASEAN Championship,Hanoi,Vietnam,0,H,2026
49545,2026-08-22,Thailand,Vietnam,0,2,ASEAN Championship,Bangkok,Thailand,0,A,2026
49546,2026-08-26,Vietnam,Thailand,2,2,ASEAN Championship,Hanoi,Vietnam,0,D,2026

In [21]:
text_cols = ['home_team', 'away_team', 'tournament', 'city', 'country']
for col in text_cols:
    df_modern[col] = df_modern[col].str.strip()

In [22]:
df_modern['month'] = df_modern['date'].dt.month
df_modern['day'] = df_modern['date'].dt.day_of_week

In [23]:
df_modern['total_goals'] = df_modern['home_score'] + df_modern['away_score']
df_modern['goal_difference'] = df_modern['home_score'] - df_modern['away_score']

In [24]:
df_modern

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result,year,month,day,total_goals,goal_difference
24062,2000-01-04,Egypt,Togo,2,1,Friendly,Aswan,Egypt,0,H,2000,1,1,3,1
24063,2000-01-07,Tunisia,Togo,7,0,Friendly,Tunis,Tunisia,0,H,2000,1,4,7,7
24064,2000-01-08,Trinidad and Tobago,Canada,0,0,Friendly,Port of Spain,Trinidad and Tobago,0,D,2000,1,5,0,0
24065,2000-01-09,Burkina Faso,Gabon,1,1,Friendly,Ouagadougou,Burkina Faso,0,D,2000,1,6,2,0
24066,2000-01-09,Guatemala,Armenia,1,1,Friendly,Los Angeles,United States,1,D,2000,1,6,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49542,2026-08-16,Malaysia,Vietnam,0,2,ASEAN Championship,Kuala Lumpur,Malaysia,0,A,2026,8,6,2,-2
49543,2026-08-18,Thailand,Singapore,1,2,ASEAN Championship,Bangkok,Thailand,0,A,2026,8,1,3,-1
49544,2026-08-19,Vietnam,Malaysia,2,0,ASEAN Championship,Hanoi,Vietnam,0,H,2026,8,2,2,2
49545,2026-08-22,Thailand,Vietnam,0,2,ASEAN Championship,Bangkok,Thailand,0,A,2026,8,5,2,-2
49546,2026-08-26,Vietnam,Thailand,2,2,ASEAN Championship,Hanoi,Vietnam,0,D,2026,8,2,4,0

In [25]:
df_modern.to_parquet("clean_results.parquet", index=False)

In [26]:
df_modern.to_csv("clean_results.csv", index=False)

In [27]:
print("Rows:", len(df_modern))
print("Columns:", len(df_modern.columns))

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nInvalid scores:")
print((df["home_score"] < 0).sum())
print((df["away_score"] < 0).sum())

print("\nInvalid team matches:")
print((df["home_team"] == df["away_team"]).sum())

print("\nInvalid results:")
print((~df["result"].isin(["H", "A", "D"])).sum())

Rows: 25485
Columns: 15

Missing values:
date          0
home_team     0
away_team     0
home_score    0
away_score    0
tournament    0
city          0
country       0
neutral       0
result        0
year          0
dtype: int64

Duplicate rows:
0

Invalid scores:
0
0

Invalid team matches:
0

Invalid results:
0

In [32]:
expected_result = df_modern.apply(
    lambda row: (
        "H" if row["home_score"] > row["away_score"]
        else "A" if row["home_score"] < row["away_score"]
        else "D"
    ),
    axis=1
)

print("Incorrect results:", (df_modern["result"] != expected_result).sum())

Incorrect results: 0

In [33]:
pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.52-cp313-cp313-win_amd64.whl.metadata (9.9 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.5-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\express\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (4.16.0)
Downloading sqlalchemy-2.0.52-cp313-cp313-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 429.3 kB/s eta 0:00:04
   --------- ------------------------------ 0.5/2.2 MB 429.3 kB/s eta 0:00:04
   -------------- ------------------------- 0.8/2.2 MB 454.7 kB/s eta 0:00:04
   -------------- ------------------------- 0.8/2.2 MB 454.7 kB/s eta 0:00:04
   ------------------- -------------------- 1.0/2.2 MB 487.7 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.2 MB 487.7 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.2 MB 487.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.2 MB 475.7 kB/s eta 0:00:02
   ------------------------ --------------- 1.3/2.2 MB 475.7 kB/s eta 0:00:02
   ------------------------ --------------- 1.3/2.2 MB 475.7 kB/s eta 0:00:02
   ------------------------ --------------- 1.3/2.2 MB 475.7 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.2 MB 437.6 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.2 MB 437.6 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.2 MB 437.6 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.2 MB 437.6 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.2 MB 414.5 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.2 MB 414.5 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.2 MB 414.5 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.2 MB 419.4 kB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 406.9 kB/s  0:00:05
Downloading greenlet-3.5.5-cp313-cp313-win_amd64.whl (324 kB)
Installing collected packages: greenlet, sqlalchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   ---------------------------------------- 2/2 [sqlalchemy]

Successfully installed greenlet-3.5.5 sqlalchemy-2.0.52
Note: you may need to restart the kernel to use updated packages.

In [35]:
pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.3.0-cp313-cp313-win_amd64.whl (70 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0
Note: you may need to restart the kernel to use updated packages.

In [37]:
import pandas as pd
import urllib
from sqlalchemy import create_engine

server_name = r'DESKTOP-BVMNIQD\MSSQLSERVEREXPRE'
database_name = 'FootballDB'

params = urllib.parse.quote_plus(
    r'DRIVER={ODBC Driver 17 for SQL Server};'
    r'SERVER=' + server_name + ';'
    r'DATABASE=' + database_name + ';'
    r'Trusted_Connection=yes;'
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

print("Loading data to SQL Server...")
df_modern.to_sql('matches', con=engine, if_exists='replace', index=False)
print("Data loaded successfully!")

query = "SELECT TOP 5 * FROM matches;"
test_df = pd.read_sql(query, con=engine)

print(test_df)

Loading data to SQL Server...
Data loaded successfully!
        date            home_team away_team  home_score  away_score  \
0 2000-01-04                Egypt      Togo           2           1
1 2000-01-07              Tunisia      Togo           7           0
2 2000-01-08  Trinidad and Tobago    Canada           0           0
3 2000-01-09         Burkina Faso     Gabon           1           1
4 2000-01-09            Guatemala   Armenia           1           1

  tournament           city              country  neutral result  year  month  \
0   Friendly          Aswan                Egypt        0      H  2000      1
1   Friendly          Tunis              Tunisia        0      H  2000      1
2   Friendly  Port of Spain  Trinidad and Tobago        0      D  2000      1
3   Friendly    Ouagadougou         Burkina Faso        0      D  2000      1
4   Friendly    Los Angeles        United States        1      D  2000      1

   day  total_goals  goal_difference
0    1            3                1
1    4            7                7
2    5            0                0
3    6            2                0
4    6            2                0